name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      TESTRAIL_URL: ${{ vars.TESTRAIL_URL }}
      TESTRAIL_USERNAME: ${{ vars.TESTRAIL_USERNAME }}
      TESTRAIL_PASSWORD: ${{ vars.TESTRAIL_PASSWORD }}
      TESTRAIL_PROJECT_ID: ${{ vars.TESTRAIL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30